version: "3"
services:
  box2adls:
    image: box2adls
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOX_USER_ID=
      - BOX_FOLDER_ID=
      - BOX_FOLDER_PATH=Utilization Reports/Daily Schedule Status Reports/2020 Reports
      - BOX_FILE_MASK=Branch Scheduled Hours Breakdown_{0}.xlsx
      - BOX_FILE_OUTNAME=Branch Scheduled Hours Breakdown.xlsx
      - ADLS_ACCOUNT_NAME=pahintegrationstorage
      - ADLS_ACCOUNT_KEY=
      - ADLS_CONTAINER_NAME=enterprisedata
      - ADLS_FOLDER_PATH=Raw/BOX Reports