version: "3"
services:
  box2adls:
    image: box2adls
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    command: "jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
    environment:
      - BOX_USER_ID=
      - BOX_FOLDER_ID=
      - BOX_FOLDER_PATH=Utilization Reports/Daily Schedule Status Reports/2020 Reports
      - BOX_FILE_MASK=Branch Scheduled Hours Breakdown_{0}.xlsx
      - BOX_FILE_RENAME=Branch Scheduled Hours Breakdown.xlsx
      - LAKE_ACCOUNT_NAME=
      - LAKE_ACCOUNT_KEY=
      - LAKE_CONTAINER_NAME=enterprisedata
      - LAKE_FOLDER_PATH=Raw/BOX Reports
    volumes:
      - ./jupyter:/opt/box_service/local